# Generated by Django 6.0.4 on 2026-05-01 09:42

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=100)),
                ('name_ru', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=20)),
                ('icon', models.CharField(default='🍳', max_length=10)),
                ('title_uz', models.CharField(default='', max_length=255)),
                ('title_ru', models.CharField(default='', max_length=255)),
                ('title_en', models.CharField(default='', max_length=255)),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_uz', models.TextField(default='')),
                ('quote_ru', models.TextField(default='')),
                ('quote_en', models.TextField(default='')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=api.models.generate_otp, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=255)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=255)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('benefits_uz', models.TextField(blank=True, default='')),
                ('benefits_ru', models.TextField(blank=True, default='')),
                ('benefits_en', models.TextField(blank=True, default='')),
                ('img', models.ImageField(blank=True, null=True, upload_to='supplements/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=255)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('instructions_uz', models.JSONField(blank=True, default=list)),
                ('instructions_ru', models.JSONField(blank=True, default=list)),
                ('instructions_en', models.JSONField(blank=True, default=list)),
                ('muscles_uz', models.JSONField(blank=True, default=list)),
                ('muscles_ru', models.JSONField(blank=True, default=list)),
                ('muscles_en', models.JSONField(blank=True, default=list)),
                ('mistakes_uz', models.JSONField(blank=True, default=list)),
                ('mistakes_ru', models.JSONField(blank=True, default=list)),
                ('mistakes_en', models.JSONField(blank=True, default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='', max_length=255)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercises', models.ManyToManyField(related_name='program_days', to='api.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
