# Generated by Django 6.0.4 on 2026-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_level_user_weekly_goal_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_week_workouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_workout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workouts_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
