# Generated by Django 6.0.4 on 2026-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_active_days_user_current_week_workouts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
