# Generated by Django 6.0.4 on 2026-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='recommended_sets',
            field=models.CharField(blank=True, default='3-4 sets, 8-12 reps', max_length=100),
        ),
    ]
