# Generated by Django 6.0.4 on 2026-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exercise_recommended_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diet',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='diet',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='quote_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='quote_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='programday',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='programday',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
