# Generated by Django 6.0.4 on 2026-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_name_ru_alter_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='dosage_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='dosage_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='dosage_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='origin_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='origin_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='origin_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='sources_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='sources_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='sources_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='timing_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='timing_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplement',
            name='timing_uz',
            field=models.TextField(blank=True, default=''),
        ),
    ]
