# Generated by Django 6.0.4 on 2026-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='program_days', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='programday',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
