# Generated by Django 6.0.4 on 2026-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_programday_exercises_alter_programday_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='new_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Email verification'), ('reset', 'Password reset'), ('change_email', 'Email change')], default='verify', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
