# Generated by Django 6.0.4 on 2026-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_nutritionlog_workoutlog_workoutexerciseentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexerciseentry',
            name='muscle_group',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('legs', 'Legs'), ('abs', 'Abs'), ('glutes', 'Glutes')], default='', max_length=20),
        ),
    ]
