# Generated by Django 6.0.4 on 2026-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprogram_userprogramday_workoutlog_program_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('snack', 'Nasta'), ('pre_workout', 'Mashqdan oldin'), ('post_workout', 'Mashqdan keyin'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_carbs_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_fat_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_protein_g',
            field=models.FloatField(default=0),
        ),
    ]
