# Generated by Django 6.0.4 on 2026-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_nutritionlog_meal_type_user_goal_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('pre_workout', 'Mashqdan oldin'), ('post_workout', 'Mashqdan keyin'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
