# Generated by Django 6.0.4 on 2026-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_nutritionlog_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
