# Generated by Django 6.0.4 on 2026-07-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_motivation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
    ]
